import { v4 as uuid } from 'uuid';

export const NavBarData = [
  {
    id: uuid(),
    Name: "Home",
    Description: "This is home button.",
    Role: "User",
    hidden: false,
    href: "/",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "About",
    Description: "This is Info about this is Website",
    Role: "User",
    hidden: true,
    href: "/about",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "GAME",
    Description: "This is GAME about this is Website",
    Role: "User",
    hidden: true,
    href: "/game",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "My Apps",
    Description: "This is My Apps in this Website",
    Role: "Private",
    hidden: false,
    href: "#",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "subOptions1",
        Description: "This is subOptions1 about this is Website",
        Role: "Private",
        hidden: false,
        href: "abc1",
        hasSubOptions: false,
      },
      {
        id: uuid(),
        Name: "subOptions2",
        Description: "This is subOptions2 about this is Website",
        Role: "Private",
        hidden: false,
        href: "abc",
        hasSubOptions: true,
      },
      {
        id: uuid(),
        Name: "subOptions3",
        Description: "This is subOptions3 about this is Website",
        Role: "Private",
        hidden: false,
        href: "/bcd",
        hasSubOptions: false,
      },
    ],
  },
  {
    id: uuid(),
    Name: "About Admin",
    Description: "This is Info about Admin this is Website",
    Role: "Admin",
    hidden: false,
    href: "fg",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "Game",
    Description: "This is My Apps in this Website",
    Role: "Private",
    hidden: false,
    href: "/game",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "Game1",
        Description: "This is subOptions1 about this is Website",
        Role: "Private",
        hidden: false,
        href: "/game1",
        hasSubOptions: false,
      },
      {
        id: uuid(),
        Name: "subOptions21",
        Description: "This is subOptions2 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: true,
      },
      {
        id: uuid(),
        Name: "subOptions3",
        Description: "This is subOptions3 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: false,
      },
    ],
  },
];
